#!/usr/bin/env bash

source "$CONFIG_DIR/themes/tokyonight"

PERCENTAGE="$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)"
CHARGING="$(pmset -g batt | grep 'AC Power')"

if [ "$PERCENTAGE" = "" ]; then
  exit 0
fi

case "${PERCENTAGE}" in
  100)   ICON="󰁹"
  ;;
  9[0-9]) ICON="󰂂"
  ;;
  8[0-9]) ICON="󰂁"
  ;;
  7[0-9]) ICON="󰂀"
  ;;
  6[0-9]) ICON="󰁿"
  ;;
  5[0-9]) ICON="󰁾"
  ;;
  4[0-9]) ICON="󰁽"
  ;;
  3[0-9]) ICON="󰁼"
  ;;
  2[0-9]) ICON="󰁻"
  ;;
  1[0-9]) ICON="󰁺"
  ;;
  *) ICON="󰂃"
esac

if [[ "$CHARGING" != "" ]]; then
  ICON="󰂄"
fi

# Lower charge = worse: blue -> yellow -> red.
if [ "$PERCENTAGE" -le 20 ]; then
  COLOR="$red"
elif [ "$PERCENTAGE" -le 50 ]; then
  COLOR="$yellow"
else
  COLOR="$blue"
fi

# The item invoking this script (name $NAME) will get its icon and label
# updated with the current battery status.
sketchybar --set "$NAME" icon="$ICON" label="${PERCENTAGE}%" \
                         icon.color="$COLOR" label.color="$COLOR" \
           --set "${NAME}_bracket" background.border_color="$COLOR"
