#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

RAM_LABEL_COLOR="$blue"
RAM_BACKGROUND_BORDER_COLOR="$blue"

sketchybar --add item ram_gap right \
           --set      ram_gap \
                      width=10 \
                      background.drawing=off

sketchybar --add item ram_spacer_right right \
           --set      ram_spacer_right \
                      background.drawing=off

sketchybar --add item ram right \
           --set      ram \
                      background.drawing=off \
                      icon="󰍛" \
                      icon.drawing=on \
                      icon.color="$RAM_LABEL_COLOR" \
                      icon.font="$LABEL_BASE_FONT:Bold:16.0" \
                      icon.padding_right=3 \
                      label.color="$RAM_LABEL_COLOR" \
                      label.padding_left=0 \
                      label.padding_right=0 \
                      update_freq=5 \
                      script="$PLUGIN_DIR/ram"

sketchybar --add item ram_spacer_left right \
           --set      ram_spacer_left \
                      background.drawing=off

sketchybar --add bracket ram_bracket ram_spacer_left ram ram_spacer_right \
           --set         ram_bracket \
                         background.border_color="$RAM_BACKGROUND_BORDER_COLOR" \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"
